### ISSUE TITLE
Organizar projeto em pastas, dividindo tipos de arquivos

### ISSUE THREAD

**Issue by cassianomon** [cassianomon/HacktoberfestUTFPR#15]

**Comment by itepifanio** [comment]
Solicitação de pull request para esta issue

**Comment by cassianomon** [comment]
Opa blz? Estou restringindo os pull requests para os alunos do curso de Eng. de Software da UTFPR, caso não seja resolvida até dia 31 eu aceito a sua.

**Comment by cassianomon** [comment]
Pode refazer essa @itepifanio ?

**Comment by itepifanio** [comment]
Trabalhando nisso
