### ISSUE TITLE
Criar organização no GitHub para projetos de alunos da UTFPR-DV e transferir este projeto para ela

### ISSUE THREAD

**Issue by cassianomon** [cassianomon/HacktoberfestUTFPR#16]

**Comment by marcusberger** [comment]
Nome da organização tem ser assim mesmo: "HacktoberfestUTFPR"?

**Comment by cassianomon** [comment]
Opa, beleza? Estou priorizando alunos da UTFPR para os pull-requests, mas obrigado pela intenção.
